@Basket_HostAddress = https://localhost:7210/basket

GET {{Basket_HostAddress}}/guru
Accept: application/json

###

POST {{Basket_HostAddress}}
Content-Type: application/json
{
    "UserName": "guru",
    "Items": [
      {
        "Quantity": 2,
        "Color": "Red",
        "Price": 0,
        "ProductId": 1,
        "ProductName": ""
      },
      {
        "Quantity": 1,
        "Color": "Blue",
        "Price": 0,
        "ProductId": 2,
        "ProductName": ""
      }
    ]
}

###

DELETE {{Basket_HostAddress}}/guru
Content-Type: application/json